<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ArtificialLife.Core/ArtificialLife.Core.csproj" />
    <ProjectReference Include="../ArtificialLife.Brain/ArtificialLife.Brain.csproj" />
    <ProjectReference Include="../ArtificialLife.Modules.Temperature/ArtificialLife.Modules.Temperature.csproj" />
  </ItemGroup>
</Project>
